version: "3.4"
services:
  web:
    image: webclimbingnew:latest
    ports:
      - 4080:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 30s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 30s
    env_file:
      - ./docker-stack-full.env

  webapi:
    image: webclimbingapi:latest
    ports:
      - 4081:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 30s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 30s
    env_file:
      - ./docker-stack-full.env

  migrator:
    image: webclimbingmigrator:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
      update_config:
        parallelism: 1
        delay: 30s
    env_file:
      - ./docker-stack-full.env

  postgres-sql-swarm:
    image: postgres:10.0
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd