version: "3.4"
services:
  web:
    image: webclimbingnew:latest
    ports:
      - 3080:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 30s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 30s
    env_file:
      - ./docker-stack.env
    networks:
      - extn

  webapi:
    image: webclimbingapi:latest
    ports:
      - 3081:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 30s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 30s
    env_file:
      - ./docker-stack.env
    networks:
      - extn

  migrator:
    image: webclimbingmigrator:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 30s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 30s
    env_file:
      - ./docker-stack.env
    networks:
      - extn
  
networks:
  extn:
    external:
      name: my-sql