version: "3.4"
services:
  postgres-server:
    image: postgres:10.0
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    networks:
      my-sql:
        aliases:
          - postgres-sql
  
networks:
  my-sql:
    external:
      name: my-sql