version: "3.2"
services:
  web:
    image: webclimbingnew:latest
    build:
      context: ../WebClimbingNew
      args:
        source: ./obj/Docker

  api:
    image: webclimbingapi:latest
    build:
      context: ../WebClimbing.Api
      args:
        source: ./obj/Docker