version: "3.2"
services:
  web:
    image: webclimbingnew:latest
    build:
      context: ../WebClimbingNew
      args:
        source: ./obj/Docker
    ports:
      - 3080:80
    env_file:
      - ./docker-compose.env
    networks:
      - sql

  api:
    image: webclimbingapi:latest
    build:
      context: ../WebClimbing.Api
      args:
        source: ./obj/Docker
    ports:
      - 3081:80
    env_file:
      - ./docker-compose.env
    networks:
      - sql

  migrator:
    image: webclimbingmigrator:latest
    build:
      context: ../MigratorService
      args:
        source: ./obj/Docker
    env_file:
      - ./docker-compose.env
    networks:
      - sql

networks:
  sql:
    external:
      name: infra_my-sql