version: "3.2"
services:
  web:
    image: webclimbingnew:latest
    container_name: web-facade
    build:
      context: ../WebClimbingNew
      args:
        source: ./obj/Docker
    ports:
      - 3080:80
    env_file:
      - ./docker-compose.env
    networks:
      - sql
      - idp-net

  api:
    image: webclimbingapi:latest
    container_name: web-api
    build:
      context: ../WebClimbing.Api
      args:
        source: ./obj/Docker
    ports:
      - 3081:80
    env_file:
      - ./docker-compose.env
    networks:
      - sql
      - idp-net

  migrator:
    image: webclimbingmigrator:latest
    container_name: migrator
    build:
      context: ../MigratorService
      args:
        source: ./obj/Docker
    env_file:
      - ./docker-compose.env
    networks:
      - sql

  idp:
    image: webclimbing-idp:latest
    container_name: web-idp
    build:
      context: ../WebClimbing.IDP
      args:
        source: ./obj/Docker
    ports:
      - 3082:80
    env_file:
      - ./docker-compose.env
    restart: unless-stopped
    networks:
      - idp-net

networks:
  sql:
    external:
      name: infra_db
  idp-net: